### ISSUE TITLE
There is just add to wishlist options. Add an option to add items to cart and then buy it.

### ISSUE THREAD

**Issue by SwarajKaondal** [SE-Fall-2024-Team-52/slash-ui#1]
The user can only add items to wishlist. Add a feature which allows them to add items to cart on the search tab and the wishlist tab.
![image](https://github.com/user-attachments/assets/df556d18-ea01-4e69-bd1b-c1693b6d93e9)

**Comment by SwarajKaondal** [comment]
Added Cart and Order page
https://github.com/SE-Fall-2024-Team-52/slash-ui/pull/3

**Comment by saisameer1998** [comment]
![image](https://github.com/user-attachments/assets/8550eb34-c52f-42f4-b8d7-c073558c2def)
Working as expected

**Comment by SwarajKaondal** [comment]
Closing, issue fixed
